# Generated by Django 4.2.6 on 2023-10-07 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userauth', '0004_user_last_login_user_password'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
